git add ./XNATSlicer/XnatSlicerLib/ui/*.py
git add ./XNATSlicer/Resources/Icons/*.png
git add ./XNATSlicer/Resources/Images/*.png
git add ./XNATSlicer/XnatSlicerLib/ui/custom-qt-widgets/*.py
git add ./XNATSlicer/XnatSlicerLib/ui/settings-widgets/*.py
git add ./XNATSlicer/XnatSlicerLib/utils/*.py
git add ./XNATSlicer/XnatSlicerLib/io/*.py
git add ./XNATSlicer/*.py
git add ./XNATSlicer/CMakeLists.txt
git add ./CMakeLists.txt
git add ./XNATSlicer/Testing/__init__.py
git add ./XNATSlicer/Testing/CMakeLists.txt
git add ./XNATSlicer/Testing/files/*
git add ./XNATSlicer/Testing/Python/CMakeLists.txt
git add ./XNATSlicer/Testing/Python/*.py
git add ./XNATSlicer/Testing/*.py
git add ./README.md
